#This code is adapted from http://learn-2-code.appspot.com/ and https://www.udacity.com/course/viewer#!/c-nd000/l-4195258602/m-3971648689

application: jbnanodegree
version: 7
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /templates
  static_dir: html_templates
  application_readable: true
- url: /.*
  script: notes.application
- url: /feedback/
  script: guestbook.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest